version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:15
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file: ./.env
